export const projects: ProjectType[] = [
  {
    id: 1,
    title: "Vectra: AI Voice Companion",
    des: "Vectra is an advanced virtual voice companion designed to provide seamless, human-like assistance across a multitude of tasks. Leveraging cutting-edge AI, it offers intuitive and responsive interactions to streamline daily operations and enhance productivity.",
    img: "https://i.ibb.co/QFFnGnvg/vectra-img.png",
    category: ["AI/ML", "Voice Technology", "Frontend Development"],
    github: "https://github.com/JCMisa/vectra",
    live: "https://vectra.vercel.app/",
  },
  {
    id: 2,
    title: "Loom: Virtual Conferencing",
    des: "Loom is a robust virtual conferencing application, meticulously crafted as a clone of Zoom. It empowers users to attend high-quality online meetings, fostering real-time collaboration and connection with participants worldwide.",
    img: "https://i.ibb.co/zV4x5WcC/loom-img.png",
    category: [
      "WebRTC",
      "Real-time Communication",
      "Full Stack",
      "Cloud Computing",
    ],
    github: "https://github.com/JCMisa/video-conferencing-app",
    live: "https://video-conferencing-app-flax.vercel.app/",
  },
  {
    id: 3,
    title: "RHU-IMS: Healthcare Inventory Management",
    des: "RHU-IMS is a specialized inventory management system developed for the Rural Health Unit of Nagcarlan, Laguna. It optimizes resource tracking and streamlines operations, ensuring efficient supply management for critical healthcare services.",
    img: "https://i.ibb.co/mCKKq7pp/rhu-img.png",
    category: [
      "Enterprise Software",
      "Database Management",
      "Healthcare Tech",
      "Backend Development",
    ],
    github: "https://github.com/JCMisa/stock-management-system-v15.3.2",
    live: "https://rhu-nagcarlan-ims.vercel.app/",
  },
  {
    id: 4,
    title: "CogniCare: Virtual Doctor Assistant",
    des: "CogniCare is an innovative virtual doctor assistant providing human-like voice interactions for online patient checkups. 'Cogni' offers personalized advice, minor prescriptions, and health suggestions, making healthcare accessible and user-friendly.",
    img: "https://i.ibb.co/66zq53y/cognicare-img.png",
    category: ["Healthcare Tech", "AI/ML", "Voice Technology", "UX Design"],
    github: "https://github.com/JCMisa/cognicare",
    live: "https://cognicare-red.vercel.app/",
  },
  {
    id: 5,
    title: "Apex: AI Mock Interviewer",
    des: "Apex is a sophisticated virtual interviewer designed to assist professionals in preparing for mock interviews. Powered by Vapi and built with Next.js, it provides realistic practice sessions to enhance confidence and performance.",
    img: "https://i.ibb.co/V0rzKyNV/apex-img.png",
    category: ["AI/ML", "Natural Language Processing", "Full Stack"],
    github: "https://github.com/JCMisa/apex",
    live: "https://apex-gold.vercel.app/",
  },
  {
    id: 6,
    title: "Meowgic: AI Logo Generator",
    des: "Meowgic is a unique logo generator application that harnesses the power of Gemini AI and Hugging Face model integration. Users can effortlessly generate distinctive logo images based on their creative prompts, bringing ideas to life visually.",
    img: "https://i.ibb.co/d4hGRZnD/meowgic-img.png",
    category: [
      "AI/ML",
      "Computer Vision",
      "Frontend Development",
      "Creative Tools",
    ],
    github: "https://github.com/JCMisa/ai-logo-maker",
    live: "https://meowgic.vercel.app/",
  },
  {
    id: 7,
    title: "Zeno: Collaborative Code Editor",
    des: "Zeno is an advanced online code editor enabling users to write, save, share, and collaborate on code in real-time. It integrates AI for intelligent code recommendations and suggestions, enhancing productivity and learning.",
    img: "https://i.ibb.co/tT6DqbgD/zeno-img.png",
    category: [
      "Developer Tools",
      "Real-time Collaboration",
      "AI/ML",
      "Full Stack",
    ],
    github: "https://github.com/JCMisa/zeno",
    live: "https://zeno-liart.vercel.app/",
  },
  {
    id: 8,
    title: "Flare: Dynamic Social Media",
    des: "Flare is a vibrant social media application inspired by platforms like X. It allows users to browse personalized feeds, engage with posts through comments and likes, and share content, all enhanced by real-time notifications and interactive actions.",
    img: "https://i.ibb.co/vCcrFqcc/flare-img.png",
    category: [
      "Social Media",
      "Real-time Features",
      "Full Stack",
      "Cloud Computing",
    ],
    github: "https://github.com/JCMisa/flare",
    live: "https://flare-beta.vercel.app/",
  },
  {
    id: 9,
    title: "Attendo: Student Attendance Tracker",
    des: "Say goodbye to attendance headaches. This cloud-based platform offers real-time tracking, time-saving automation, and valuable insights to optimize your operations.",
    img: "https://i.ibb.co/nq3kmbm9/attendo-img.png",
    category: ["Education Tech", "Database Management", "Analytics"],
    github: "https://github.com/JCMisa/attendance-tracker",
    live: "https://attendance-tracker-xi.vercel.app/",
  },
  {
    id: 10,
    title: "DocSync: Real-time Document Collaboration",
    des: "DocSync is a powerful Google Docs clone that facilitates real-time collaboration on single documents. Users can collectively edit, add comments, and manage sharing authorities, enhancing teamwork and productivity for shared projects.",
    img: "https://i.ibb.co/3YMDXSDh/docsync-img.png",
    category: [
      "Productivity Tools",
      "Real-time Collaboration",
      "Cloud Computing",
    ],
    github: "https://github.com/JCMisa/realtime-app",
    live: "https://docsync-flax.vercel.app/",
  },
  {
    id: 11,
    title: "Medly: Online Hospital Appointments",
    des: "Medly is a user-friendly online hospital appointment application. It empowers patients to easily schedule appointments with available doctors, streamlining the booking process and improving access to healthcare services.",
    img: "https://i.ibb.co/twYTWsps/medly-img.png",
    category: ["Healthcare Tech", "Appointment Systems", "Full Stack"],
    github: "https://github.com/JCMisa/medly",
    live: "https://medly.vercel.app/",
  },
  {
    id: 12,
    title: "IdeAI: AI Content Creation",
    des: "IdeAI is an innovative online SaaS platform that enables users to generate diverse content across multiple categories, including coding, blogs, YouTube scripts, and articles. Content creation is seamlessly powered by Gemini AI integration, fostering creativity and efficiency.",
    img: "https://i.ibb.co/7N2YD6b7/ideai-img.png",
    category: ["AI/ML", "Content Generation", "SaaS"],
    github: "https://github.com/JCMisa/ai-content-generator",
    live: "https://ide-ai-theta.vercel.app/",
  },
  {
    id: 13,
    title: "Pensieve: AI Personalized Courses",
    des: "Pensieve is an AI-powered platform designed to help users create their personalized courses. Leveraging artificial intelligence, it intelligently generates comprehensive course content based on user inputs, tailoring educational experiences to individual needs.",
    img: "https://i.ibb.co/99sgCyyF/pensieve-img.png",
    category: ["Education Tech", "AI/ML", "Content Generation"],
    github: "https://github.com/JCMisa/ai-course-generator",
    live: "https://pensieve-topaz.vercel.app/",
  },
  {
    id: 14,
    title: "FinTechFlow: Personal Finance Manager",
    des: "FinTechFlow is a robust finance website project dedicated to effective expense management. It allows users to clearly identify their earnings and accurately deduct expenses from their current budget, promoting financial control and awareness.",
    img: "https://i.ibb.co/Ngjch040/fintechflow-img.png",
    category: ["FinTech", "Personal Finance", "Data Analytics"],
    github: "https://github.com/JCMisa/expense-tracker",
    live: "https://fin-tech-flow.vercel.app/",
  },
  {
    id: 15,
    title: "JCM Portfolio (old version): Animated E-Portfolio",
    des: "JCM Portfolio (old version) is an engaging e-portfolio showcasing state-of-the-art animations and design. It also integrates robust backend support, allowing users to sign in and contribute their own testimonials, creating an interactive and dynamic experience.",
    img: "https://i.ibb.co/8hvXVP4/jcm-portfolio-old-img.png",
    category: ["Frontend Development", "UI/UX Design", "Animation"],
    github: "https://github.com/JCMisa/portfolio-fullstack",
    live: "https://official-portfolio-sigma.vercel.app/",
  },
  {
    id: 16,
    title: "Ignite: Startup Showcase Platform",
    des: "Ignite is an innovative application designed to spark ideas and ignite businesses. It allows users to showcase their startups and enables others to vote on different ventures, leveraging powerful Next.js features like SSR, SSG, and ISR for optimal performance.",
    img: "https://i.ibb.co/rf09Kj3b/ignite-img.png",
    category: ["Startup Tech", "Full Stack", "Community Platform"],
    github: "https://github.com/JCMisa/ignite",
    live: "https://ignite-ruby.vercel.app/",
  },
  {
    id: 17,
    title: "cAIre: AI Symptom Checker",
    des: "cAIre is an AI-driven project developed for a Gemini API competition. It allows users to input their symptoms, and the AI model intelligently determines possible reasons, identifies potential diseases, suggests additional symptoms, recommends medicines, and provides personalized patient advice.",
    img: "https://i.ibb.co/RGbcLNTK/caire-img.png",
    category: ["Healthcare Tech", "AI/ML", "Diagnostic Tools"],
    github: "https://github.com/JCMisa/caire-gemini",
    live: "https://caire.vercel.app/",
  },
  {
    id: 18,
    title: "AIIM: AI Interview Mocker",
    des: "AIIM (AI Interview Mocker) is an AI-powered platform designed to help employees practice their interview sessions. The virtual AI asks relevant questions and even evaluates the interview performance, providing valuable feedback for improvement.",
    img: "https://i.ibb.co/Qt59thb/aiim-img.png",
    category: ["AI/ML", "Career Development", "Education Tech"],
    github: "https://github.com/JCMisa/ai-interview-mocker",
    live: "https://misa-interview-mocker.vercel.app/",
  },
  {
    id: 19,
    title: "Apple Website Clone: Pixel-Perfect Web Clone",
    des: "This project is a meticulous clone of the Apple website, demonstrating mastery of modern frontend technologies. It leverages the power of Next.js and advanced frontend tools like ShadCN, GSAP, Three.js, and Framer Motion to achieve pixel-perfect fidelity and smooth animations.",
    img: "https://i.ibb.co/ycsr45xp/apple-clone-img.png",
    category: [
      "Frontend Development",
      "UI/UX Design",
      "Animation",
      "Web Performance",
    ],
    github: "https://github.com/JCMisa/apple-website",
    live: "https://apple-website-misa.vercel.app/",
  },
  {
    id: 20,
    title: "ReUp: AI Resume Builder",
    des: "ReUp is an intelligent resume builder application powered by AI. It efficiently generates professional resumes based on user inputs such as experience, skills, and qualifications, streamlining the job application process.",
    img: "https://i.ibb.co/mVfbbHvn/reup-img.png",
    category: ["AI/ML", "Career Development", "Document Generation"],
    github: "https://github.com/JCMisa/ai-resume-builder",
    live: "https://misa-ai-resume-builder.vercel.app/",
  },
  {
    id: 21,
    title: "CuraTech: Hospital Management System",
    des: "CuraTech is a comprehensive online hospital management system where patients can conveniently book appointments with their doctors. It leverages robust Next.js tools, Zod for form validations, and React Hook Forms, featuring state-of-the-art email notifications and a beautiful dashboard.",
    img: "https://i.ibb.co/CKzPrf0K/curatech-img.png",
    category: ["Healthcare Tech", "Enterprise Software", "Full Stack"],
    github: "https://github.com/JCMisa/CuraTech-HealthCare",
    live: "https://cura-tech-health-care.vercel.app/",
  },
  {
    id: 22,
    title: "Flux: University Library System",
    des: "Flux is a modern university library system designed for online book borrowing. It includes advanced features like rate limiting and queuing to manage high demand, ensuring a smooth and efficient experience for all users.",
    img: "https://i.ibb.co/kgCpFjkQ/flux-img.png",
    category: ["Education Tech", "Library Management", "Backend Development"],
    github: "https://github.com/JCMisa/university-library",
    live: "https://flux-university-library.vercel.app/",
  },
  {
    id: 23,
    title: "SOU: Org Submission Streamliner",
    des: "SOU automates and simplifies the complex process of submitting requirements for new student organizations at the university. This platform streamlines every step, from document compilation to approval workflows, ensuring a seamless and efficient experience for students and administration alike.",
    img: "https://i.ibb.co/bjKkd6mP/sou-img.jpg",
    category: ["Education Tech", "Workflow Automation", "Document Management"],
    github: "https://github.com/JCMisa/SOUFinalProject",
  },
  {
    id: 24,
    title: "Aora: Video Sharing Platform",
    des: "Aora is a dynamic video posting app, enabling users to effortlessly share, discover, and engage with content. Users can like and save videos from a vibrant community, fostering a seamless and interactive media experience. Powered by React Native.",
    category: ["Mobile Development", "Social Media", "Video Streaming"],
    github: "https://github.com/JCMisa/react-native-crashcourse",
  },
  {
    id: 25,
    title: "PurrfectlyMatch: Pet Adoption Platform",
    des: "PurrfectlyMatch is a compassionate mobile application dedicated to connecting pets with loving homes. It streamlines the online pet adoption process, allowing users to browse, learn about, and adopt pets conveniently and responsibly. Powered by React Native.",
    category: ["Mobile Development", "Community Platform", "Pet Tech"],
    github: "https://github.com/JCMisa/pet-adoption-mobile-app",
  },
  {
    id: 26,
    title: "TechTrail: AI Learning Platform",
    des: "TechTrail is an innovative Learning Management System (LMS) powered by the Gemini AI model. It revolutionizes education by automatically generating tailored course content and providing personalized student reviewers, optimizing learning pathways and enhancing retention.",
    img: "https://i.ibb.co/9HPkjLck/techtrail-img.jpg",
    category: ["Education Tech", "AI/ML", "E-Learning"],
    github: "https://github.com/JCMisa/techtrail-lms",
    live: "https://techtrail-gamma.vercel.app/",
  },
  {
    id: 27,
    title: "ReStop: B2B Restaurant Platform",
    des: "ReStop is a comprehensive web application empowering B2B restaurants to establish their online presence, manage orders, and streamline operations. Built with Spring Boot and React, it provides robust features for displaying menus, processing online payments, and efficient store management, connecting restaurants directly with their customers.",
    img: "https://i.ibb.co/LhqskzBB/restop-img.jpg",
    category: ["B2B Platform", "Food Tech", "E-Commerce"],
    github: "https://github.com/JCMisa/SpringBoot-FoodOrderingApp",
  },
  {
    id: 28,
    title: "DictionAIry: AI Dictionary & Chat",
    des: "DictionAIry is an intelligent web application providing instant access to comprehensive word definitions, synonyms, and antonyms via an integrated dictionary API. It features audio pronunciations for enhanced learning, complemented by a built-in AI chatbot for interactive language assistance and exploration.",
    img: "https://i.ibb.co/wZRxq4cw/dictionairy-img.png",
    category: ["AI/ML", "Education Tech", "Language Learning"],
    github: "https://github.com/JCMisa/dictionAIry",
  },
  {
    id: 29,
    title: "Finatica: Global Investment Insights",
    des: "Finatica is a powerful web application built with React and .NET Web API, designed to empower users with comprehensive investment analysis. By integrating global company APIs, it fetches vital financial information, guiding users to make informed investment decisions and maximize potential gains in specific companies.",
    img: "https://i.ibb.co/xtqpChgM/finatica-img.png",
    category: ["FinTech", "Data Analytics", "Investment Tools"],
    github: "https://github.com/JCMisa/Finatica",
  },
  {
    id: 30,
    title: "Netflix Clone: Movie Streaming Clone",
    des: "This app is a robust web application meticulously crafted as a Netflix clone, leveraging React and powerful API integrations. It allows users to browse, search, and watch a vast library of movies and TV shows, delivering a familiar and seamless entertainment experience.",
    img: "https://i.ibb.co/Jw8hVFbR/netflix-clone-img.png",
    category: ["Video Streaming", "Frontend Development", "Entertainment Tech"],
    github: "https://github.com/JCMisa/netflix-clone",
  },
  {
    id: 31,
    title: "Gemini Clone: Conversational AI Interface",
    des: "This application is a direct clone of Google's Gemini LLM, allowing users to interact with the powerful AI model. It provides a seamless interface for asking questions, receiving comprehensive responses, and leveraging Gemini's capabilities for diverse conversational and generative tasks.",
    img: "https://i.ibb.co/PsxgcnTm/gemini-clone-img.jpg",
    category: ["AI/ML", "Natural Language Processing", "Chatbot"],
    github: "https://github.com/JCMisa/gemini-clone",
  },
  {
    id: 32,
    title: "Spotify Clone: Music Streaming Platform",
    des: "RhythmStream is a modern music streaming application, meticulously built with React and Tailwind CSS. It features a fully integrated audio player, allowing users to effortlessly discover and enjoy their favorite songs with a sleek, intuitive interface.",
    img: "https://i.ibb.co/LX0wzsj0/spotify-clone-img.jpg",
    category: ["Music Streaming", "Frontend Development", "Entertainment Tech"],
    github: "https://github.com/JCMisa/spotify-clone-misa",
  },
];

export const certificates = [
  {
    id: 1,
    img: "https://i.ibb.co/ccLY73Vp/Great-Stack-Certificate.png",
    title: "Great-Stack-Certificate",
  },
  {
    id: 2,
    img: "https://i.ibb.co/3yLb5v19/ethical-hacker-badge-img-misa.png",
    title: "ethical-hacker-badge-img-misa",
  },
  {
    id: 3,
    img: "https://i.ibb.co/B5c6ZP8b/etichal-hacker-cert.jpg",
    title: "ethical-hacker-cert",
  },
  {
    id: 4,
    img: "https://i.ibb.co/Q3NX3mRB/Data-Analytics-Cerificate.jpg",
    title: "Data-Analytics-Certificate",
  },
  {
    id: 5,
    img: "https://i.ibb.co/C3pqh5rW/user-experience-design-fundamentals-badge-img-misa.png",
    title: "user-experience-design-fundamentals-badge",
  },
  {
    id: 6,
    img: "https://i.ibb.co/DHFK56VK/ux-design-cert.jpg",
    title: "ux-design-cert",
  },
  {
    id: 7,
    img: "https://i.ibb.co/21p07xRX/networking-devices-and-initial-configuration-badge-img-misa.png",
    title: "networking-devices-and-initial-configuration-badge",
  },
  {
    id: 8,
    img: "https://i.ibb.co/XdVyVY0/net-device-cert.jpg",
    title: "net-device-cert",
  },
  {
    id: 9,
    img: "https://i.ibb.co/pvZ850CY/misa-project-management-fundamentals-badge-img.png",
    title: "project-management-fundamentals-badge",
  },
  {
    id: 10,
    img: "https://i.ibb.co/TqkbYfYk/intro-to-llm-cert.jpg",
    title: "intro-to-llm-cert",
  },
  {
    id: 11,
    img: "https://i.ibb.co/TBYTk0wm/intro-to-data-analytics-cert.jpg",
    title: "intro-to-data-analytics-cert",
  },
  {
    id: 12,
    img: "https://i.ibb.co/fYCNf3L5/intro-to-cloud-computing-cert.jpg",
    title: "intro-to-cloud-computing-cert",
  },
  {
    id: 13,
    img: "https://i.ibb.co/XZLDJJkK/business-analytics-with-excel-cert.jpg",
    title: "business-analytics-with-excel-cert",
  },
  {
    id: 14,
    img: "https://i.ibb.co/239xr2rN/misa-badge-img-web-development-fundamentals.png",
    title: "web-development-fundamentals-badge",
  },
  {
    id: 15,
    img: "https://i.ibb.co/Lh627gpT/web-test-and-deployment-cert.jpg",
    title: "web-test-and-deployment-cert",
  },
  {
    id: 16,
    img: "https://i.ibb.co/s9n6H3DW/web-dev-basics-cert.jpg",
    title: "web-dev-basics-cert",
  },
  {
    id: 17,
    img: "https://i.ibb.co/602W8YYF/web-dev-fundamentals-cert.jpg",
    title: "web-dev-fundamentals-cert",
  },
  {
    id: 18,
    img: "https://i.ibb.co/C4jrCNP/proj-mngmnt-fundamentals-cert.jpg",
    title: "project-management-fundamentals-cert",
  },
  {
    id: 19,
    img: "https://i.ibb.co/23Kx2b7T/intro-to-html-css-cert.jpg",
    title: "intro-to-html-css-cert",
  },
  {
    id: 20,
    img: "https://i.ibb.co/KxdM4Jpt/developing-sites-for-the-web-cert.jpg",
    title: "developing-sites-for-the-web-cert",
  },
  {
    id: 21,
    img: "https://i.ibb.co/0pQG6g5k/bringing-websites-to-life-with-js-cert.jpg",
    title: "bringing-websites-to-life-with-js-cert",
  },
  {
    id: 22,
    img: "https://i.ibb.co/cSYrBPZd/javascript-essentials-1-badge-img-misa.png",
    title: "javascript-essentials-1-badge",
  },
  {
    id: 23,
    img: "https://i.ibb.co/Myp0sWCy/js-essentials-1-cert.jpg",
    title: "js-essentials-1-cert",
  },
  {
    id: 24,
    img: "https://i.ibb.co/ccLY73Vp/Great-Stack-Certificate.png",
    title: "Great-Stack-Certificate",
  },
];
