export const projects: ProjectType[] = [
  {
    id: 1,
    title: "Vectra: AI Voice Companion",
    des: "Vectra is an advanced virtual voice companion designed to provide seamless, human-like assistance across a multitude of tasks. Leveraging cutting-edge AI, it offers intuitive and responsive interactions to streamline daily operations and enhance productivity.",
    img: "https://i.ibb.co/QFFnGnvg/vectra-img.png",
    iconLists: ["php.svg", "js.png", "html.svg", "css.svg", "sql.png"],
    github: "https://github.com/JCMisa/vectra",
    live: "https://vectra.vercel.app/",
  },
  {
    id: 2,
    title: "Loom: Virtual Conferencing",
    des: "Loom is a robust virtual conferencing application, meticulously crafted as a clone of Zoom. It empowers users to attend high-quality online meetings, fostering real-time collaboration and connection with participants worldwide.",
    img: "https://i.ibb.co/zV4x5WcC/loom-img.png",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/stream.svg", "/c.svg"],
    github: "https://github.com/JCMisa/video-conferencing-app",
    live: "https://video-conferencing-app-flax.vercel.app/",
  },
  {
    id: 3,
    title: "RHU-IMS: Healthcare Inventory Management",
    des: "RHU-IMS is a specialized inventory management system developed for the Rural Health Unit of Nagcarlan, Laguna. It optimizes resource tracking and streamlines operations, ensuring efficient supply management for critical healthcare services.",
    img: "https://i.ibb.co/mCKKq7pp/rhu-img.png",
    iconLists: [
      "/re.svg",
      "/tail.svg",
      "/ts.svg",
      "/appwrite.jpeg",
      "/twilio.svg",
    ],
    github: "https://github.com/JCMisa/stock-management-system-v15.3.2",
    live: "https://rhu-nagcarlan-ims.vercel.app/",
  },
  {
    id: 4,
    title: "CogniCare: Virtual Doctor Assistant",
    des: "CogniCare is an innovative virtual doctor assistant providing human-like voice interactions for online patient checkups. 'Cogni' offers personalized advice, minor prescriptions, and health suggestions, making healthcare accessible and user-friendly.",
    img: "https://i.ibb.co/66zq53y/cognicare-img.png",
    iconLists: ["/re.svg", "/tail.svg", "/js.png", "/three.svg", "/gsap.svg"],
    github: "https://github.com/JCMisa/cognicare",
    live: "https://cognicare-red.vercel.app/",
  },
  {
    id: 5,
    title: "Apex: AI Mock Interviewer",
    des: "Apex is a sophisticated virtual interviewer designed to assist professionals in preparing for mock interviews. Powered by Vapi and built with Next.js, it provides realistic practice sessions to enhance confidence and performance.",
    img: "https://i.ibb.co/V0rzKyNV/apex-img.png",
    iconLists: [
      "/next.svg",
      "/tail.svg",
      "/gemini.svg",
      "/neondb.png",
      "/drizzle.png",
    ],
    github: "https://github.com/JCMisa/apex",
    live: "https://apex-gold.vercel.app/",
  },
  {
    id: 6,
    title: "Meowgic: AI Logo Generator",
    des: "Meowgic is a unique logo generator application that harnesses the power of Gemini AI and Hugging Face model integration. Users can effortlessly generate distinctive logo images based on their creative prompts, bringing ideas to life visually.",
    img: "https://i.ibb.co/d4hGRZnD/meowgic-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/gemini.svg",
      "/neondb.png",
      "/drizzle.png",
    ],
    github: "https://github.com/JCMisa/ai-logo-maker",
    live: "https://meowgic.vercel.app/",
  },
  {
    id: 7,
    title: "Zeno: Collaborative Code Editor",
    des: "Zeno is an advanced online code editor enabling users to write, save, share, and collaborate on code in real-time. It integrates AI for intelligent code recommendations and suggestions, enhancing productivity and learning.",
    img: "https://i.ibb.co/tT6DqbgD/zeno-img.png",
    iconLists: [
      "/next.svg",
      "/liveblocks.png",
      "/sentry.png",
      "/shadcn.png",
      "/tail.svg",
    ],
    github: "https://github.com/JCMisa/zeno",
    live: "https://zeno-liart.vercel.app/",
  },
  {
    id: 8,
    title: "Flare: Dynamic Social Media",
    des: "Flare is a vibrant social media application inspired by platforms like X. It allows users to browse personalized feeds, engage with posts through comments and likes, and share content, all enhanced by real-time notifications and interactive actions.",
    img: "https://i.ibb.co/vCcrFqcc/flare-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/flare",
    live: "https://flare-beta.vercel.app/",
  },
  {
    id: 9,
    title: "Attendo: Student Attendance Tracker",
    des: "Say goodbye to attendance headaches. This cloud-based platform offers real-time tracking, time-saving automation, and valuable insights to optimize your operations.",
    img: "https://i.ibb.co/nq3kmbm9/attendo-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/attendance-tracker",
    live: "https://attendance-tracker-xi.vercel.app/",
  },
  {
    id: 10,
    title: "DocSync: Real-time Document Collaboration",
    des: "DocSync is a powerful Google Docs clone that facilitates real-time collaboration on single documents. Users can collectively edit, add comments, and manage sharing authorities, enhancing teamwork and productivity for shared projects.",
    img: "https://i.ibb.co/3YMDXSDh/docsync-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/realtime-app",
    live: "https://docsync-flax.vercel.app/",
  },

  {
    id: 11,
    title: "Medly: Online Hospital Appointments",
    des: "Medly is a user-friendly online hospital appointment application. It empowers patients to easily schedule appointments with available doctors, streamlining the booking process and improving access to healthcare services.",
    img: "https://i.ibb.co/twYTWsps/medly-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/medly",
    live: "https://medly.vercel.app/",
  },
  {
    id: 12,
    title: "IdeAI: AI Content Creation",
    des: "IdeAI is an innovative online SaaS platform that enables users to generate diverse content across multiple categories, including coding, blogs, YouTube scripts, and articles. Content creation is seamlessly powered by Gemini AI integration, fostering creativity and efficiency.",
    img: "https://i.ibb.co/7N2YD6b7/ideai-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/ai-content-generator",
    live: "https://ide-ai-theta.vercel.app/",
  },
  {
    id: 13,
    title: "Pensieve: AI Personalized Courses",
    des: "Pensieve is an AI-powered platform designed to help users create their personalized courses. Leveraging artificial intelligence, it intelligently generates comprehensive course content based on user inputs, tailoring educational experiences to individual needs.",
    img: "https://i.ibb.co/99sgCyyF/pensieve-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/ai-course-generator",
    live: "https://pensieve-topaz.vercel.app/",
  },
  {
    id: 14,
    title: "FinTechFlow: Personal Finance Manager",
    des: "FinTechFlow is a robust finance website project dedicated to effective expense management. It allows users to clearly identify their earnings and accurately deduct expenses from their current budget, promoting financial control and awareness.",
    img: "https://i.ibb.co/Ngjch040/fintechflow-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/expense-tracker",
    live: "https://fin-tech-flow.vercel.app/",
  },
  {
    id: 15,
    title: "JCM Portfolio (old version): Animated E-Portfolio",
    des: "JCM Portfolio (old version) is an engaging e-portfolio showcasing state-of-the-art animations and design. It also integrates robust backend support, allowing users to sign in and contribute their own testimonials, creating an interactive and dynamic experience.",
    img: "https://i.ibb.co/8hvXVP4/jcm-portfolio-old-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/portfolio-fullstack",
    live: "https://official-portfolio-sigma.vercel.app/",
  },
  {
    id: 16,
    title: "Ignite: Startup Showcase Platform",
    des: "Ignite is an innovative application designed to spark ideas and ignite businesses. It allows users to showcase their startups and enables others to vote on different ventures, leveraging powerful Next.js features like SSR, SSG, and ISR for optimal performance.",
    img: "https://i.ibb.co/rf09Kj3b/ignite-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/ignite",
    live: "https://ignite-ruby.vercel.app/",
  },
  {
    id: 17,
    title: "cAIre: AI Symptom Checker",
    des: "cAIre is an AI-driven project developed for a Gemini API competition. It allows users to input their symptoms, and the AI model intelligently determines possible reasons, identifies potential diseases, suggests additional symptoms, recommends medicines, and provides personalized patient advice.",
    img: "https://i.ibb.co/RGbcLNTK/caire-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/caire-gemini",
    live: "https://caire.vercel.app/",
  },
  {
    id: 18,
    title: "AIIM: AI Interview Mocker",
    des: "AIIM (AI Interview Mocker) is an AI-powered platform designed to help employees practice their interview sessions. The virtual AI asks relevant questions and even evaluates the interview performance, providing valuable feedback for improvement.",
    img: "https://i.ibb.co/Qt59thb/aiim-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/ai-interview-mocker",
    live: "https://misa-interview-mocker.vercel.app/",
  },
  {
    id: 19,
    title: "Apple Website Clone: Pixel-Perfect Web Clone",
    des: "This project is a meticulous clone of the Apple website, demonstrating mastery of modern frontend technologies. It leverages the power of Next.js and advanced frontend tools like ShadCN, GSAP, Three.js, and Framer Motion to achieve pixel-perfect fidelity and smooth animations.",
    img: "https://i.ibb.co/ycsr45xp/apple-clone-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/apple-website",
    live: "https://apple-website-misa.vercel.app/",
  },
  {
    id: 20,
    title: "ReUp: AI Resume Builder",
    des: "ReUp is an intelligent resume builder application powered by AI. It efficiently generates professional resumes based on user inputs such as experience, skills, and qualifications, streamlining the job application process.",
    img: "https://i.ibb.co/mVfbbHvn/reup-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/ai-resume-builder",
    live: "https://misa-ai-resume-builder.vercel.app/",
  },
  {
    id: 21,
    title: "CuraTech: Hospital Management System",
    des: "CuraTech is a comprehensive online hospital management system where patients can conveniently book appointments with their doctors. It leverages robust Next.js tools, Zod for form validations, and React Hook Forms, featuring state-of-the-art email notifications and a beautiful dashboard.",
    img: "https://i.ibb.co/CKzPrf0K/curatech-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/CuraTech-HealthCare",
    live: "https://cura-tech-health-care.vercel.app/",
  },
  {
    id: 22,
    title: "Flux: University Library System",
    des: "Flux is a modern university library system designed for online book borrowing. It includes advanced features like rate limiting and queuing to manage high demand, ensuring a smooth and efficient experience for all users.",
    img: "https://i.ibb.co/kgCpFjkQ/flux-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/university-library",
    live: "https://flux-university-library.vercel.app/",
  },
  {
    id: 23,
    title: "SOU: Org Submission Streamliner",
    des: "SOU automates and simplifies the complex process of submitting requirements for new student organizations at the university. This platform streamlines every step, from document compilation to approval workflows, ensuring a seamless and efficient experience for students and administration alike.",
    img: "https://i.ibb.co/bjKkd6mP/sou-img.jpg",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/SOUFinalProject",
  },
  {
    id: 24,
    title: "Aora: Video Sharing Platform",
    des: "Aora is a dynamic video posting app, enabling users to effortlessly share, discover, and engage with content. Users can like and save videos from a vibrant community, fostering a seamless and interactive media experience. Powered by React Native.",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/react-native-crashcourse",
  },
  {
    id: 25,
    title: "PurrfectlyMatch: Pet Adoption Platform",
    des: "PurrfectlyMatch is a compassionate mobile application dedicated to connecting pets with loving homes. It streamlines the online pet adoption process, allowing users to browse, learn about, and adopt pets conveniently and responsibly. Powered by React Native.",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/pet-adoption-mobile-app",
  },
  {
    id: 26,
    title: "TechTrail: AI Learning Platform",
    des: "TechTrail is an innovative Learning Management System (LMS) powered by the Gemini AI model. It revolutionizes education by automatically generating tailored course content and providing personalized student reviewers, optimizing learning pathways and enhancing retention.",
    img: "https://i.ibb.co/9HPkjLck/techtrail-img.jpg",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/techtrail-lms",
    live: "https://techtrail-gamma.vercel.app/",
  },
  {
    id: 27,
    title: "ReStop: B2B Restaurant Platform",
    des: "ReStop is a comprehensive web application empowering B2B restaurants to establish their online presence, manage orders, and streamline operations. Built with Spring Boot and React, it provides robust features for displaying menus, processing online payments, and efficient store management, connecting restaurants directly with their customers.",
    img: "https://i.ibb.co/LhqskzBB/restop-img.jpg",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/SpringBoot-FoodOrderingApp",
  },
  {
    id: 28,
    title: "DictionAIry: AI Dictionary & Chat",
    des: "DictionAIry is an intelligent web application providing instant access to comprehensive word definitions, synonyms, and antonyms via an integrated dictionary API. It features audio pronunciations for enhanced learning, complemented by a built-in AI chatbot for interactive language assistance and exploration.",
    img: "https://i.ibb.co/wZRxq4cw/dictionairy-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/dictionAIry",
  },
  {
    id: 29,
    title: "Finatica: Global Investment Insights",
    des: "Finatica is a powerful web application built with React and .NET Web API, designed to empower users with comprehensive investment analysis. By integrating global company APIs, it fetches vital financial information, guiding users to make informed investment decisions and maximize potential gains in specific companies.",
    img: "https://i.ibb.co/xtqpChgM/finatica-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/Finatica",
  },
  {
    id: 30,
    title: "Netflix Clone: Movie Streaming Clone",
    des: "This app is a robust web application meticulously crafted as a Netflix clone, leveraging React and powerful API integrations. It allows users to browse, search, and watch a vast library of movies and TV shows, delivering a familiar and seamless entertainment experience.",
    img: "https://i.ibb.co/Jw8hVFbR/netflix-clone-img.png",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/netflix-clone",
  },
  {
    id: 31,
    title: "Gemini Clone: Conversational AI Interface",
    des: "This application is a direct clone of Google's Gemini LLM, allowing users to interact with the powerful AI model. It provides a seamless interface for asking questions, receiving comprehensive responses, and leveraging Gemini's capabilities for diverse conversational and generative tasks.",
    img: "https://i.ibb.co/PsxgcnTm/gemini-clone-img.jpg",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/gemini-clone",
  },
  {
    id: 32,
    title: "Spotify Clone: Music Streaming Platform",
    des: "RhythmStream is a modern music streaming application, meticulously built with React and Tailwind CSS. It features a fully integrated audio player, allowing users to effortlessly discover and enjoy their favorite songs with a sleek, intuitive interface.",
    img: "https://i.ibb.co/LX0wzsj0/spotify-clone-img.jpg",
    iconLists: [
      "/next.svg",
      "/c.svg",
      "/neondb.png",
      "/drizzle.png",
      "/recharts.png",
    ],
    github: "https://github.com/JCMisa/spotify-clone-misa",
  },
];
